export AUTOFEATURE=true
export RSPEC=true
alias ai='sudo apt-get install'
alias autospec='autospec 2> /dev/null'
alias gs='git status'
alias gp='git push'
alias gc='git commit -m'
alias gb='git branch'
alias gaa='git add -A'
alias spec='spec -c'
